apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-java-blocking
  labels:
    app: api-java-blocking
spec:
  selector:
    matchLabels:
      app: api-java-blocking
  replicas: 4
  template:
    metadata:
      labels:
        app: api-java-blocking
    spec:
      containers:
        - name: api-java-blocking
          image: api_java_blocking
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: API_ACCOUNTS
              value: http://legacy-backend-rust.legacy-backend-rust/accounts
            - name: API_CARDS
              value: http://legacy-backend-rust.legacy-backend-rust/cards
            - name: API_CUSTOMER
              value: http://legacy-backend-rust.legacy-backend-rust/customer
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "2000Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 20
            timeoutSeconds: 10
